### ISSUE TITLE
Copying same-page links to other pages raises IndexError in _update_link_tag

### ISSUE THREAD

**Issue by introt** [zim-desktop-wiki/zim-desktop-wiki#1769]
**Describe the bug**

Links like `[[#link|Link text]]` can't be copied/moved between pages.

**To Reproduce**
1. Create a same-page link like this: `[[#link|Link text]]`
2. Select the link
3. Use Move Selected Text (or copy & try to paste in another page)
4. See error (popup with MST and/or in log)

**Expected behavior**
The link gets pasted/moved (and updated).

**Environment (please complete the following information):**
 - Version 0.74.2 (both release and dev)
 - OS: linux

**Additional context**

https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1730#issuecomment-962667546; might get fixed by #1626?

**Comment by jaap-karssenberg** [comment]
Cannot reproduce either master or develop branch. Could it be fixed with
the last commit already ?

-- Jaap

**Comment by introt** [comment]
Sidenote: Could you please not let `develop` fall behind `master`? Some great QoL fixes from `master` are missing from the former.

-----

I can still reproduce with the latest master:

```
This is zim 0.74.2
Platform: posix
Locale: en_US UTF-8
FS encoding: utf-8
Python: (3, 9, 7, 'final', 0)
PyGObject: (3, 40, 1)

======= Traceback =======
  File "/home/user/zim-desktop-wiki/zim/gui/widgets.py", line 3086, in do_response
    destroy = self.do_response_ok()
  File "/home/user/zim-desktop-wiki/zim/gui/pageview/__init__.py", line 8541, in do_response_ok
    update_parsetree_and_copy_images(parsetree, self.notebook, self.page, newpage)
  File "/home/user/zim-desktop-wiki/zim/notebook/content_updater.py", line 25, in update_parsetree_and_copy_images
    replace_parsetree_links_and_copy_images(parsetree, notebook, newpath)
  File "/home/user/zim-desktop-wiki/zim/notebook/content_updater.py", line 94, in replace_parsetree_links_and_copy_images
    parsetree.replace(
  File "/home/user/zim-desktop-wiki/zim/formats/__init__.py", line 668, in replace
    self._replace(self._etree.getroot(), tags, func)
  File "/home/user/zim-desktop-wiki/zim/formats/__init__.py", line 685, in _replace
    self._replace(child, tags, func) # recurs
  File "/home/user/zim-desktop-wiki/zim/formats/__init__.py", line 679, in _replace
    replacement = func(Element.new_from_etree(child))
  File "/home/user/zim-desktop-wiki/zim/notebook/content_updater.py", line 168, in _replace_links_to_page_and_copy_images
    return notebook._update_link_tag(node, new_path, target, oldhref)
  File "/home/user/zim-desktop-wiki/zim/notebook/notebook.py", line 803, in _update_link_tag
    elif elt.gettext() == oldhref.parts()[-1] and len(elt) == 1:
IndexError: list index out of range
```

On `develop`, I can paste the link to other pages just fine, but Move Selected Text raises the same error.

On master, when pasting the link here I get `[[#level-4-header|Level 4 header]]`, but on develop, I get `test:format test#level-4-header`.

**Comment by introt** [comment]
I can not reproduce either issue with #1626

**Comment by introt** [comment]
Can still (even accidentally) reproduce on `develop`:

1. Create pages ":test:A" and ":test:B"
2. Open ":test:B" and create the following link: `[[#B|Text]]`
3. Try to copy the link to ":test:A"
4. See error in log:

```
DEBUG: Action: paste
DEBUG: Targets available for paste: [Gdk.Atom.intern("TIMESTAMP", False), Gdk.Atom.intern("TARGETS", False), Gdk.Atom.intern("MULTIPLE", False), Gdk.Atom.intern("SAVE_TARGETS", False), Gdk.Atom.intern("UTF8_STRING", False), Gdk.Atom.intern("COMPOUND_TEXT", False), Gdk.Atom.intern("TEXT", False), Gdk.Atom.intern("STRING", False), Gdk.Atom.intern("text/plain;charset=utf-8", False), Gdk.Atom.intern("text/plain", False)], we want parsetree
DEBUG: Requesting data for ('text/x-zim-parsetree', 0, 1) -- using set_with_data() workaround
Traceback (most recent call last):
  File "/home/introt/repos/zim-desktop-wiki/zim/gui/pageview/__init__.py", line 4171, in do_paste_clipboard
    self.get_buffer().paste_clipboard(Clipboard, None, self.get_editable(), text_format=format)
  File "/home/introt/repos/zim-desktop-wiki/zim/gui/pageview/__init__.py", line 3406, in paste_clipboard
    parsetree = clipboard.get_parsetree(self.notebook, self.page, text_format)
  File "/home/introt/repos/zim-desktop-wiki/zim/gui/clipboard.py", line 643, in get_parsetree
    return parsetree_from_selectiondata(selectiondata, notebook, path, text_format)
  File "/home/introt/repos/zim-desktop-wiki/zim/gui/clipboard.py", line 227, in parsetree_from_selectiondata
    return replace_parsetree_links_and_copy_images(parsetree, notebook, path)
  File "/home/introt/repos/zim-desktop-wiki/zim/notebook/content_updater.py", line 91, in replace_parsetree_links_and_copy_images
    return parsetree.substitute_elements(
  File "/home/introt/repos/zim-desktop-wiki/zim/formats/__init__.py", line 656, in substitute_elements
    replacement = func(TokenListElement(t[0], t[1], content))
  File "/home/introt/repos/zim-desktop-wiki/zim/notebook/content_updater.py", line 156, in _replace_links_to_page_and_copy_images
    return notebook._update_link_tag(node, new_path, target, oldhref)
  File "/home/introt/repos/zim-desktop-wiki/zim/notebook/notebook.py", line 801, in _update_link_tag
    elif elt.content == [(TEXT, oldhref.parts()[-1])]:
IndexError: list index out of range
```

Not with #1626 though:

```
DEBUG: Action: paste
DEBUG: Targets available for paste: [Gdk.Atom.intern("TIMESTAMP", False), Gdk.Atom.intern("TARGETS", False), Gdk.Atom.intern("MULTIPLE", False), Gdk.Atom.intern("SAVE_TARGETS", False), Gdk.Atom.intern("UTF8_STRING", False), Gdk.Atom.intern("COMPOUND_TEXT", False), Gdk.Atom.intern("TEXT", False), Gdk.Atom.intern("STRING", False), Gdk.Atom.intern("text/plain;charset=utf-8", False), Gdk.Atom.intern("text/plain", False)], we want parsetree
DEBUG: Requesting data for ('text/x-zim-parsetree', 0, 1) -- using set_with_data() workaround
DEBUG: Store page in background: test:B
```
