### ISSUE TITLE
Search with only 1000 files is slow

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#881]
I'm not sure why, but this is the case. 
This is on a modern 2019 computer with 12 cores.
Am I doing something wrong? How come zim doesn't do fulltext indexing, only tags and titles?

**Comment by jaap-karssenberg** [comment]
Zim is a volunteer project so if you find it leaving in some aspects please
don't ask "how come". If you would like to work on such feature it would be
very welcome.

Op wo 19 jun. 2019 17:37 schreef Jose Quesada <notifications@github.com>:

**Comment by galenthurber** [comment]
I have had this problem >0.70
it was caused by storing notes with many @ 
such as email addresses and twitter handles.
zim would try to cross index way too many loops threads etc

**Comment by quesada** [comment]
Interesting, @galenthurber . So it could be a problem with the indexing algorithm.
@jaap-karssenberg I admire what you are doing, and I think zim has made really good design decisions. I'll keep using it but I cannot contribute to the codebase now or anytime soon. Point taken on the 'how come' thing.

**Comment by Nick222** [comment]
How about use Recoll for fast search from inside Zim ? May be it plugin-idea ?

**Comment by quesada** [comment]
I'm using recoll right now.
One other option is rg, or any grep subsitute. They are damn fast.
Something extra would be to have advanced queries, like sorting by date. The one tool that has that down pat (tags that are numeric or dates, and sortable) is trilium.

**Comment by javadevelopment4** [comment]
Is the search issue got fixed in the recent version ? Does it supports 2,000 note files or nodes with instant search for a word?

**Comment by pfalcon** [comment]
> Zim is a volunteer project so if you find it leaving in some aspects please
don't ask "how come".

Well, there's a question of knowing what Zim does and what Zim doesn't. I for example was sure to read Zim docs, but I'm still not sure if it maintains full-text index or not. According to such bug reports, it doesn't, but it would be nice to have some "official" (perhaps, technical-oriented) docs explaining what Zim does and what doesn't, and how (aka architectural docs).

**Comment by introt** [comment]
Duplicate of #64
